version: '3.8'
services: 
 db:
    image: mysql:8.0.28
    restart: always 
    container_name: mysql
    environment:
      - MYSQL_DATABASE=user_db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      -  mysql_db:/var/lib/mysql
    networks:
      - main_network
volumes:
  mysql_db:
    name: mysql_db 

networks:
  main_network:
    name: main_network
