version: '3' 
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - 8089:8080
    volumes:
      - .:/golang-docker
    depends_on:
      - database
    container_name: golang-docker-web
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'
     

  database:
    image: mysql:8.0.28
    restart: always 
    container_name: mysql
    environment:
      - MYSQL_DATABASE=user_db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      -  mysql_db:/var/lib/mysql
    networks:
      - main_network

  pma:
    image: go-mysql:01
    depends_on:
      - database
    ports:
      - 5003:80
    environment:
      - 'PMA_HOST=database'
      - 'PMA_PORT=3306'
    container_name: golang-docker-pma

volumes:
  mysql_db:
    name: mysql_db 

networks:
  main_network:
    name: main_network